### ISSUE TITLE
Log4j FileNotFoundException

### ISSUE THREAD

**Issue by vberihuete** [vberihuete/MailLib#1]
The lib is throwing an error trying to find a log4j file

**Comment by reynoldmorel** [comment]
![email exception](https://cloud.githubusercontent.com/assets/6406348/6883546/31e65d6e-d588-11e4-9d63-b5438f4635cd.PNG)

**Comment by vberihuete** [comment]
Fixed within e4d2b85874a4dfd44945d30bc491c2afe69f04c4
